name: flanker-test
on:
  push:

jobs:
  create-env:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9 
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          miniconda-version: "latest"

      - name: Verify Conda installation
        run: |
          ls -l /usr/local/miniconda/condabin/conda || echo "Conda not installed"

      - name: Initialize Conda for the shell
        run: |
          conda init bash  # Initialize Conda for bash shell
          source ~/.bashrc  # Apply the initialization

      - name: Update Conda
        run: |
          conda update -n base -c defaults conda -y

      - name: Create and Activate Environment
        run: |
          conda env create -f flanker-test.yml --name flanker-test
          conda activate flanker-test
          conda info --envs

      - name: Install Dependencies
        run: |
          conda activate flanker-test
          conda install pytest -y
          pip install .

      - name: Run Tests
        run: |
          conda activate flanker-test
          pytest -s
