name: Tests
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.6, 3.9]
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: conda-forge, bioconda
      - name: Install
        run: |
          conda install mamba=1.1.0 -n base -c conda-forge
          mamba create -n flanker-test -c bioconda python=3.7 abricate=1.0.1 pandas=1.2 biopython=1.78  mash=2.2.2 networkx=2.5 python-levenshtein=0.12.2
          mamba activate flanker-test
          pip install .
      - name: Test
        run: |
          pytest -s

