name: flanker-test
on:
  push:

    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        python-version: ["3.9"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: flanker
          environment-file: flanker-test.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          conda-remove-defaults: true
      - run: pip install .
      - run: python -m pytest
