name: flanker-test
on:
  push:

jobs:
  create-env:
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.6, 3.9]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Update Conda
        run: conda update -n base -c defaults conda
        
      - name: Python ${{ matrix.python-version }} (${{ matrix.os }})
        uses: actions/checkout@v2
      
      - name: Create environment with Mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          activate-environment: flanker-test
          environment-file: flanker-test.yml
                
      - name: Check solution
        run: |
          conda --version
          mamba --version
          mamba env export
          
      - name: Build flanker environment
        run: |
          mamba activate flanker-test
          mamba install pytest
          pip install .       
          
      - name: Run tests
        run: |
          pytest -s
