name: flanker-test
on:
  push:

jobs:
  create-env:
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.6, 3.9]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
        
    steps:
        
      - name: Python ${{ matrix.python-version }} (${{ matrix.os }})
        uses: actions/checkout@v2
            
      - name: Verify Conda installation
        run: ls -l /usr/local/miniconda/condabin/conda
  
      - name: Update Conda
        run: conda update -n base -c defaults conda
      
      - name: Create environment with Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          activate-environment: flanker-test
          environment-file: flanker-test.yml
                
      - name: Check solution
        run: |
          conda --version
          
      - name: Build flanker environment
        run: |
          conda activate flanker-test
          conda install pytest
          pip install .       
          
      - name: Run tests
        run: |
          pytest -s
