name: Tests
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.6, 3.9]
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge, bioconda
          python-version: ${{ matrix.python-version }}
          activate-environment: flanker-test
          environment-file: flanker-test.yml
          use-mamba: true     
      - name: Check solution
        run: |
          mamba env export
      - name: Build flanker environment
        run: |
          mamba activate flanker-test
          mamba install pytest
          pip install .         
      - name: Test
        run: |
          pytest -s
