name: flanker-test
on:
  push:

jobs:
  create-env:
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.9]
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          miniconda-version: "latest"  # Specify Miniconda version

      - name: Verify Conda installation
        run: |
          ls -l /usr/local/miniconda/condabin/conda || echo "Conda not installed"

      - name: Update Conda
        run: |
          conda update -n base -c defaults conda -y

      - name: Create and Activate Environment
        run: |
          conda env create -f flanker-test.yml --name flanker-test
          conda activate flanker-test
          conda info --envs

      - name: Install Dependencies
        run: |
          conda activate flanker-test
          conda install pytest -y
          pip install .

      - name: Run Tests
        run: |
          conda activate flanker-test
          pytest -s
